site_name: OSROOM DOC
site_url: https://osroom.com
repo_url: https://github.com/osroom/osroom-doc
site_author: Allen Woo
pages:
    - 文档: index.md
    - 安装部署:
        - 安装: app/install.md
        - 部署: app/deploy.md
        - Mongodb安装: app/mongodb.md
        - Redis安装: app/redis.md
    - Api文档:
        - Api请求验证: api/api_call.md
        - Api说明文档: api/api_doc.md
    - 插件|主题:
        - 插件开发: plugin/index.md
        - 主题开发: theme/index.md

site_dir: 'osr/v1.0'

extra:
    version: 1.0
    search:
      language: 'jp'
theme:
    name: readthedocs
    custom_dir: 'simplex'

plugins:
    - search
copyright: Allen Woo
site_description: OSROOM开源Web系统|CMF文档, OSROOM可用于搭建企业官网, 个人网站, 微信小程序后端等
